inputs = [
    {
        "optimal": False,
        "turns_to_go": 40,
        "map": [
            ['P', 'P', 'P', 'P', 'P'],
            ['P', 'P', 'P', 'P', 'P'],
            ['P', 'I', 'P', 'P', 'P'],
            ['P', 'I', 'P', 'P', 'P'],
            ['P', 'P', 'P', 'I', 'I'],
            ['I', 'P', 'P', 'P', 'P'],
            ['P', 'P', 'P', 'P', 'P'],
        ],
        "wizards": {'Wizard_0': {"location": (5, 1)},
                    'Wizard_1': {"location": (0, 4)}},
        "horcrux": {'Horcrux_0': {"location": (2, 4),
                               "possible_locations": ((2, 4), (1, 3), (0, 2), (6, 3), (4, 0)),
                               "prob_change_location": 0.58},
                    'Horcrux_1': {"location": (2, 2),
                               "possible_locations": ((2, 2), (1, 0), (6, 3), (4, 1)),
                               "prob_change_location": 0.58}},
        "death_eaters": {'DeathEater_0': {"index": 0,
                                           "path": [(1, 3), (0, 3), (0, 4), (0, 3), (1, 3), (2, 3)]},
                        'DeathEater_1': {"index": 0,
                                           "path": [(0, 2), (1, 2), (2, 2), (2, 3)]}},
    },
    {
        "optimal": False,
        "turns_to_go": 40,
        "map": [
            ['I', 'P', 'I', 'P', 'P'],
            ['P', 'P', 'P', 'P', 'P'],
            ['P', 'P', 'P', 'P', 'P'],
            ['P', 'P', 'P', 'I', 'P'],
            ['P', 'P', 'P', 'P', 'P'],
            ['P', 'P', 'I', 'P', 'I'],
            ['P', 'P', 'P', 'P', 'P'],
        ],
        "wizards": {'Wizard_0': {"location": (4, 4)},
                    'Wizard_1': {"location": (3, 2)},
                    'Wizard_2': {"location": (6, 3)}},
        "horcrux": {'Horcrux_0': {"location": (3, 1),
                               "possible_locations": ((3, 1), (6, 3)),
                               "prob_change_location": 0.39},
                    'Horcrux_1': {"location": (4, 3),
                               "possible_locations": ((4, 3), (4, 2), (5, 0), (6, 0)),
                               "prob_change_location": 0.47},
                    'Horcrux_2': {"location": (2, 2),
                               "possible_locations": ((2, 2), (5, 3), (6, 4)),
                               "prob_change_location": 0.29}},
        "death_eaters": {'DeathEater_0': {"index": 0,
                                           "path": [(5, 0), (4, 0), (4, 1)]},
                        'DeathEater_1': {"index": 0,
                                           "path": [(2, 4), (1, 4), (2, 4)]},
                        'DeathEater_2': {"index": 0,
                                           "path": [(6, 4), (6, 3), (6, 4), (6, 3)]}},
    },
    {
        "optimal": False,
        "turns_to_go": 30,
        "map": [
            ['P', 'P', 'P', 'P', 'P', 'I', 'P'],
            ['I', 'P', 'P', 'P', 'P', 'P', 'P'],
            ['P', 'P', 'P', 'P', 'P', 'I', 'P'],
            ['I', 'P', 'I', 'P', 'P', 'P', 'P'],
            ['P', 'P', 'P', 'P', 'I', 'P', 'P'],
            ['P', 'P', 'P', 'P', 'P', 'P', 'P'],
        ],
        "wizards": {'Wizard_0': {"location": (3, 5)},
                    'Wizard_1': {"location": (0, 0)}},
        "horcrux": {'Horcrux_0': {"location": (5, 5),
                               "possible_locations": ((5, 5), (4, 1), (3, 3), (4, 0)),
                               "prob_change_location": 0.95},
                    'Horcrux_1': {"location": (2, 4),
                               "possible_locations": ((2, 4), (4, 1), (1, 1)),
                               "prob_change_location": 0.19},
                    'Horcrux_2': {"location": (4, 3),
                               "possible_locations": ((4, 3), (2, 6)),
                               "prob_change_location": 0.59},
                    'Horcrux_3': {"location": (2, 0),
                               "possible_locations": ((2, 0), (2, 6)),
                               "prob_change_location": 0.86}},
        "death_eaters": {'DeathEater_0': {"index": 0,
                                           "path": [(4, 5), (5, 5), (5, 4), (5, 5)]},
                        'DeathEater_1': {"index": 0,
                                           "path": [(1, 5), (1, 4), (0, 4), (1, 4), (0, 4)]},
                        'DeathEater_2': {"index": 0,
                                           "path": [(1, 6), (0, 6), (1, 6), (0, 6), (1, 6)]},
                        'DeathEater_3': {"index": 0,
                                           "path": [(1, 6), (1, 5), (1, 6), (2, 6)]}},
    },
    {
        "optimal": False,
        "turns_to_go": 30,
        "map": [
            ['P', 'P', 'P', 'I', 'P', 'P', 'P'],
            ['P', 'P', 'P', 'P', 'P', 'I', 'P'],
            ['P', 'P', 'P', 'P', 'P', 'P', 'P'],
            ['P', 'I', 'P', 'P', 'P', 'I', 'P'],
            ['P', 'P', 'I', 'P', 'P', 'P', 'P'],
        ],
        "wizards": {'Wizard_0': {"location": (0, 1)},
                    'Wizard_1': {"location": (3, 2)},
                    'Wizard_2': {"location": (0, 2)}},
        "horcrux": {'Horcrux_0': {"location": (2, 0),
                               "possible_locations": ((2, 0), (0, 4), (2, 5)),
                               "prob_change_location": 0.89},
                    'Horcrux_1': {"location": (4, 6),
                               "possible_locations": ((4, 6), (2, 6)),
                               "prob_change_location": 0.57},
                    'Horcrux_2': {"location": (1, 4),
                               "possible_locations": ((1, 4), (3, 3), (2, 2)),
                               "prob_change_location": 0.19}},
        "death_eaters": {'DeathEater_0': {"index": 0,
                                           "path": [(1, 2), (2, 2), (1, 2)]},
                        'DeathEater_1': {"index": 0,
                                           "path": [(0, 4), (1, 4), (2, 4), (1, 4)]}},
    },
    {
        "optimal": False,
        "turns_to_go": 10,
        "map": [
            ['P', 'I', 'P', 'P', 'P', 'P'],
            ['P', 'I', 'P', 'P', 'I', 'P'],
            ['P', 'P', 'P', 'P', 'P', 'P'],
            ['P', 'P', 'P', 'P', 'P', 'P'],
            ['P', 'P', 'P', 'P', 'P', 'I'],
        ],
        "wizards": {'Wizard_0': {"location": (4, 2)},
                    'Wizard_1': {"location": (0, 3)},
                    'Wizard_2': {"location": (4, 4)}},
        "horcrux": {'Horcrux_0': {"location": (2, 5),
                               "possible_locations": ((2, 5), (3, 3), (2, 1)),
                               "prob_change_location": 0.23},
                    'Horcrux_1': {"location": (4, 3),
                               "possible_locations": ((4, 3), (4, 1), (3, 3)),
                               "prob_change_location": 0.29}},
        "death_eaters": {'DeathEater_0': {"index": 0,
                                           "path": [(3, 3), (4, 3), (4, 2)]},
                        'DeathEater_1': {"index": 0,
                                           "path": [(2, 3), (1, 3), (0, 3), (0, 2), (1, 2)]},
                        'DeathEater_2': {"index": 0,
                                           "path": [(2, 3), (2, 2), (1, 2)]},
                        'DeathEater_3': {"index": 0,
                                           "path": [(0, 3), (0, 4), (0, 5)]}},
    },
    {
        "optimal": False,
        "turns_to_go": 20,
        "map": [
            ['P', 'I', 'P', 'P', 'P'],
            ['P', 'P', 'P', 'P', 'P'],
            ['P', 'P', 'P', 'P', 'P'],
            ['I', 'P', 'P', 'P', 'P'],
            ['P', 'P', 'P', 'P', 'P'],
        ],
        "wizards": {'Wizard_0': {"location": (1, 1)},
                    'Wizard_1': {"location": (2, 3)}},
        "horcrux": {'Horcrux_0': {"location": (0, 4),
                               "possible_locations": ((0, 4), (0, 3), (2, 1), (3, 2), (2, 4)),
                               "prob_change_location": 0.97},
                    'Horcrux_1': {"location": (1, 4),
                               "possible_locations": ((1, 4), (2, 3)),
                               "prob_change_location": 0.7},
                    'Horcrux_2': {"location": (0, 4),
                               "possible_locations": ((0, 4), (3, 2), (1, 0)),
                               "prob_change_location": 0.96},
                    'Horcrux_3': {"location": (2, 4),
                               "possible_locations": ((2, 4), (1, 1), (4, 0)),
                               "prob_change_location": 0.57}},
        "death_eaters": {'DeathEater_0': {"index": 0,
                                           "path": [(4, 3), (3, 3), (3, 4), (3, 3), (2, 3), (2, 2)]},
                        'DeathEater_1': {"index": 0,
                                           "path": [(1, 4), (0, 4), (0, 3), (1, 3), (0, 3), (1, 3)]},
                        'DeathEater_2': {"index": 0,
                                           "path": [(3, 3), (4, 3), (4, 2), (4, 3)]},
                        'DeathEater_3': {"index": 0,
                                           "path": [(2, 2), (3, 2), (4, 2), (4, 3), (3, 3)]}},
    },
    {
        "optimal": False,
        "turns_to_go": 20,
        "map": [
            ['P', 'P', 'P', 'P', 'P'],
            ['P', 'P', 'P', 'P', 'P'],
            ['P', 'P', 'I', 'P', 'P'],
            ['P', 'P', 'P', 'P', 'P'],
            ['P', 'P', 'P', 'P', 'I'],
        ],
        "wizards": {'Wizard_0': {"location": (2, 1)},
                    'Wizard_1': {"location": (0, 0)},
                    'Wizard_2': {"location": (2, 4)}},
        "horcrux": {'Horcrux_0': {"location": (3, 1),
                               "possible_locations": ((3, 1), (2, 0)),
                               "prob_change_location": 0.86},
                    'Horcrux_1': {"location": (0, 2),
                               "possible_locations": ((0, 2), (1, 0), (3, 3)),
                               "prob_change_location": 0.11}},
        "death_eaters": {'DeathEater_0': {"index": 0,
                                           "path": [(1, 3), (1, 2), (1, 3), (1, 2)]},
                        'DeathEater_1': {"index": 0,
                                           "path": [(2, 0), (1, 0), (0, 0), (1, 0), (2, 0), (1, 0)]},
                        'DeathEater_2': {"index": 0,
                                           "path": [(1, 1), (2, 1), (2, 0), (3, 0), (4, 0), (3, 0)]}},
    },
    {
        "optimal": False,
        "turns_to_go": 30,
        "map": [
            ['P', 'P', 'P', 'P', 'P'],
            ['P', 'P', 'P', 'P', 'I'],
            ['P', 'P', 'P', 'I', 'P'],
            ['P', 'P', 'P', 'P', 'P'],
            ['P', 'I', 'P', 'P', 'P'],
            ['I', 'P', 'P', 'I', 'P'],
            ['P', 'P', 'P', 'P', 'P'],
        ],
        "wizards": {'Wizard_0': {"location": (4, 3)},
                    'Wizard_1': {"location": (0, 0)}},
        "horcrux": {'Horcrux_0': {"location": (3, 1),
                               "possible_locations": ((3, 1), (3, 3), (5, 1), (2, 0)),
                               "prob_change_location": 0.6},
                    'Horcrux_1': {"location": (2, 4),
                               "possible_locations": ((2, 4), (1, 0), (2, 0), (3, 0), (0, 1)),
                               "prob_change_location": 0.53},
                    'Horcrux_2': {"location": (5, 4),
                               "possible_locations": ((5, 4), (6, 0), (6, 3), (3, 3), (4, 3)),
                               "prob_change_location": 0.93},
                    'Horcrux_3': {"location": (4, 0),
                               "possible_locations": ((4, 0), (0, 1), (4, 4), (6, 3), (6, 2)),
                               "prob_change_location": 0.26}},
        "death_eaters": {'DeathEater_0': {"index": 0,
                                           "path": [(2, 1), (3, 1), (2, 1)]},
                        'DeathEater_1': {"index": 0,
                                           "path": [(4, 0), (3, 0), (2, 0), (2, 1)]}},
    },
    {
        "optimal": False,
        "turns_to_go": 20,
        "map": [
            ['I', 'P', 'P', 'P', 'P', 'P'],
            ['P', 'P', 'P', 'P', 'P', 'P'],
            ['I', 'P', 'I', 'P', 'P', 'P'],
            ['P', 'P', 'P', 'P', 'I', 'P'],
            ['P', 'P', 'P', 'P', 'P', 'P'],
        ],
        "wizards": {'Wizard_0': {"location": (0, 1)},
                    'Wizard_1': {"location": (4, 1)}},
        "horcrux": {'Horcrux_0': {"location": (1, 5),
                               "possible_locations": ((1, 5), (0, 4), (3, 0)),
                               "prob_change_location": 0.72},
                    'Horcrux_1': {"location": (0, 2),
                               "possible_locations": ((0, 2), (3, 3), (1, 4), (0, 3), (1, 1)),
                               "prob_change_location": 0.43},
                    'Horcrux_2': {"location": (1, 0),
                               "possible_locations": ((1, 0), (0, 1), (3, 1)),
                               "prob_change_location": 0.98},
                    'Horcrux_3': {"location": (1, 0),
                               "possible_locations": ((1, 0), (3, 2), (3, 5)),
                               "prob_change_location": 0.4}},
        "death_eaters": {'DeathEater_0': {"index": 0,
                                           "path": [(2, 5), (1, 5), (0, 5), (1, 5), (0, 5), (0, 4)]},
                        'DeathEater_1': {"index": 0,
                                           "path": [(0, 5), (1, 5), (1, 4), (1, 5)]},
                        'DeathEater_2': {"index": 0,
                                           "path": [(1, 1), (0, 1), (0, 2), (0, 3)]},
                        'DeathEater_3': {"index": 0,
                                           "path": [(1, 2), (1, 3), (1, 2)]}},
    },
    {
        "optimal": False,
        "turns_to_go": 20,
        "map": [
            ['P', 'P', 'I', 'I', 'P', 'P', 'P'],
            ['P', 'P', 'P', 'P', 'P', 'P', 'P'],
            ['I', 'P', 'P', 'P', 'P', 'P', 'P'],
            ['P', 'P', 'P', 'P', 'P', 'P', 'I'],
            ['P', 'P', 'I', 'P', 'P', 'P', 'P'],
        ],
        "wizards": {'Wizard_0': {"location": (0, 1)},
                    'Wizard_1': {"location": (4, 0)},
                    'Wizard_2': {"location": (4, 3)}},
        "horcrux": {'Horcrux_0': {"location": (2, 1),
                               "possible_locations": ((2, 1), (3, 0), (3, 1)),
                               "prob_change_location": 0.07},
                    'Horcrux_1': {"location": (4, 6),
                               "possible_locations": ((4, 6), (0, 4)),
                               "prob_change_location": 0.89}},
        "death_eaters": {'DeathEater_0': {"index": 0,
                                           "path": [(0, 0), (1, 0), (0, 0), (0, 1)]},
                        'DeathEater_1': {"index": 0,
                                           "path": [(0, 4), (0, 5), (0, 4)]},
                        'DeathEater_2': {"index": 0,
                                           "path": [(4, 0), (3, 0), (4, 0), (3, 0), (4, 0), (3, 0)]},
                        'DeathEater_3': {"index": 0,
                                           "path": [(2, 2), (3, 2), (2, 2), (2, 3), (3, 3)]}},
    },
]